//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace EnterpriseServices.SecurityService.API.OrgService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrganizationServiceSoap", Namespace="urn:Masterduner@Yeah.net")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DbHelper))]
    public partial class OrganizationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRootOrganizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrganizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubOrganizationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrganizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPositionCollectionExcludeSpecifiedOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateStaffOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEnabledStaffsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssociatedAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrganizationService() {
            this.Url = global::EnterpriseServices.SecurityService.API.Properties.Settings.Default.EH_Security_OpenAPIs_SDK_OrgService_OrganizationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRootOrganizationCompletedEventHandler GetRootOrganizationCompleted;
        
        /// <remarks/>
        public event CreateOrganizationCompletedEventHandler CreateOrganizationCompleted;
        
        /// <remarks/>
        public event GetSubOrganizationsCompletedEventHandler GetSubOrganizationsCompleted;
        
        /// <remarks/>
        public event UpdateOrganizationCompletedEventHandler UpdateOrganizationCompleted;
        
        /// <remarks/>
        public event CreatePositionCompletedEventHandler CreatePositionCompleted;
        
        /// <remarks/>
        public event GetPositionCollectionExcludeSpecifiedCompletedEventHandler GetPositionCollectionExcludeSpecifiedCompleted;
        
        /// <remarks/>
        public event UpdatePositionCompletedEventHandler UpdatePositionCompleted;
        
        /// <remarks/>
        public event CreateStaffCompletedEventHandler CreateStaffCompleted;
        
        /// <remarks/>
        public event GetEnabledStaffsCompletedEventHandler GetEnabledStaffsCompleted;
        
        /// <remarks/>
        public event GetAssociatedAccountCompletedEventHandler GetAssociatedAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetRootOrganization", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Organization GetRootOrganization() {
            object[] results = this.Invoke("GetRootOrganization", new object[0]);
            return ((Organization)(results[0]));
        }
        
        /// <remarks/>
        public void GetRootOrganizationAsync() {
            this.GetRootOrganizationAsync(null);
        }
        
        /// <remarks/>
        public void GetRootOrganizationAsync(object userState) {
            if ((this.GetRootOrganizationOperationCompleted == null)) {
                this.GetRootOrganizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRootOrganizationOperationCompleted);
            }
            this.InvokeAsync("GetRootOrganization", new object[0], this.GetRootOrganizationOperationCompleted, userState);
        }
        
        private void OnGetRootOrganizationOperationCompleted(object arg) {
            if ((this.GetRootOrganizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRootOrganizationCompleted(this, new GetRootOrganizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/CreateOrganization", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateOrganization(Organization obj) {
            this.Invoke("CreateOrganization", new object[] {
                        obj});
        }
        
        /// <remarks/>
        public void CreateOrganizationAsync(Organization obj) {
            this.CreateOrganizationAsync(obj, null);
        }
        
        /// <remarks/>
        public void CreateOrganizationAsync(Organization obj, object userState) {
            if ((this.CreateOrganizationOperationCompleted == null)) {
                this.CreateOrganizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrganizationOperationCompleted);
            }
            this.InvokeAsync("CreateOrganization", new object[] {
                        obj}, this.CreateOrganizationOperationCompleted, userState);
        }
        
        private void OnCreateOrganizationOperationCompleted(object arg) {
            if ((this.CreateOrganizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrganizationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetSubOrganizations", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrganizationObjectBase[] GetSubOrganizations(string organizationOpenID) {
            object[] results = this.Invoke("GetSubOrganizations", new object[] {
                        organizationOpenID});
            return ((OrganizationObjectBase[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubOrganizationsAsync(string organizationOpenID) {
            this.GetSubOrganizationsAsync(organizationOpenID, null);
        }
        
        /// <remarks/>
        public void GetSubOrganizationsAsync(string organizationOpenID, object userState) {
            if ((this.GetSubOrganizationsOperationCompleted == null)) {
                this.GetSubOrganizationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubOrganizationsOperationCompleted);
            }
            this.InvokeAsync("GetSubOrganizations", new object[] {
                        organizationOpenID}, this.GetSubOrganizationsOperationCompleted, userState);
        }
        
        private void OnGetSubOrganizationsOperationCompleted(object arg) {
            if ((this.GetSubOrganizationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubOrganizationsCompleted(this, new GetSubOrganizationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/UpdateOrganization", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateOrganization(Organization org) {
            this.Invoke("UpdateOrganization", new object[] {
                        org});
        }
        
        /// <remarks/>
        public void UpdateOrganizationAsync(Organization org) {
            this.UpdateOrganizationAsync(org, null);
        }
        
        /// <remarks/>
        public void UpdateOrganizationAsync(Organization org, object userState) {
            if ((this.UpdateOrganizationOperationCompleted == null)) {
                this.UpdateOrganizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrganizationOperationCompleted);
            }
            this.InvokeAsync("UpdateOrganization", new object[] {
                        org}, this.UpdateOrganizationOperationCompleted, userState);
        }
        
        private void OnUpdateOrganizationOperationCompleted(object arg) {
            if ((this.UpdateOrganizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrganizationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/CreatePosition", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreatePosition(Position obj, bool isPrincipal, bool force) {
            object[] results = this.Invoke("CreatePosition", new object[] {
                        obj,
                        isPrincipal,
                        force});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePositionAsync(Position obj, bool isPrincipal, bool force) {
            this.CreatePositionAsync(obj, isPrincipal, force, null);
        }
        
        /// <remarks/>
        public void CreatePositionAsync(Position obj, bool isPrincipal, bool force, object userState) {
            if ((this.CreatePositionOperationCompleted == null)) {
                this.CreatePositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePositionOperationCompleted);
            }
            this.InvokeAsync("CreatePosition", new object[] {
                        obj,
                        isPrincipal,
                        force}, this.CreatePositionOperationCompleted, userState);
        }
        
        private void OnCreatePositionOperationCompleted(object arg) {
            if ((this.CreatePositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePositionCompleted(this, new CreatePositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetPositionCollectionExcludeSpecified", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Position[] GetPositionCollectionExcludeSpecified(System.Guid thisPositionID) {
            object[] results = this.Invoke("GetPositionCollectionExcludeSpecified", new object[] {
                        thisPositionID});
            return ((Position[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPositionCollectionExcludeSpecifiedAsync(System.Guid thisPositionID) {
            this.GetPositionCollectionExcludeSpecifiedAsync(thisPositionID, null);
        }
        
        /// <remarks/>
        public void GetPositionCollectionExcludeSpecifiedAsync(System.Guid thisPositionID, object userState) {
            if ((this.GetPositionCollectionExcludeSpecifiedOperationCompleted == null)) {
                this.GetPositionCollectionExcludeSpecifiedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionCollectionExcludeSpecifiedOperationCompleted);
            }
            this.InvokeAsync("GetPositionCollectionExcludeSpecified", new object[] {
                        thisPositionID}, this.GetPositionCollectionExcludeSpecifiedOperationCompleted, userState);
        }
        
        private void OnGetPositionCollectionExcludeSpecifiedOperationCompleted(object arg) {
            if ((this.GetPositionCollectionExcludeSpecifiedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionCollectionExcludeSpecifiedCompleted(this, new GetPositionCollectionExcludeSpecifiedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/UpdatePosition", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdatePosition(Position position, bool updateState, bool isPrincipal, System.Guid superiorPositionID) {
            this.Invoke("UpdatePosition", new object[] {
                        position,
                        updateState,
                        isPrincipal,
                        superiorPositionID});
        }
        
        /// <remarks/>
        public void UpdatePositionAsync(Position position, bool updateState, bool isPrincipal, System.Guid superiorPositionID) {
            this.UpdatePositionAsync(position, updateState, isPrincipal, superiorPositionID, null);
        }
        
        /// <remarks/>
        public void UpdatePositionAsync(Position position, bool updateState, bool isPrincipal, System.Guid superiorPositionID, object userState) {
            if ((this.UpdatePositionOperationCompleted == null)) {
                this.UpdatePositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePositionOperationCompleted);
            }
            this.InvokeAsync("UpdatePosition", new object[] {
                        position,
                        updateState,
                        isPrincipal,
                        superiorPositionID}, this.UpdatePositionOperationCompleted, userState);
        }
        
        private void OnUpdatePositionOperationCompleted(object arg) {
            if ((this.UpdatePositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePositionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/CreateStaff", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateStaff(Staff person) {
            this.Invoke("CreateStaff", new object[] {
                        person});
        }
        
        /// <remarks/>
        public void CreateStaffAsync(Staff person) {
            this.CreateStaffAsync(person, null);
        }
        
        /// <remarks/>
        public void CreateStaffAsync(Staff person, object userState) {
            if ((this.CreateStaffOperationCompleted == null)) {
                this.CreateStaffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateStaffOperationCompleted);
            }
            this.InvokeAsync("CreateStaff", new object[] {
                        person}, this.CreateStaffOperationCompleted, userState);
        }
        
        private void OnCreateStaffOperationCompleted(object arg) {
            if ((this.CreateStaffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateStaffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetEnabledStaffs", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Staff[] GetEnabledStaffs(string openID) {
            object[] results = this.Invoke("GetEnabledStaffs", new object[] {
                        openID});
            return ((Staff[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEnabledStaffsAsync(string openID) {
            this.GetEnabledStaffsAsync(openID, null);
        }
        
        /// <remarks/>
        public void GetEnabledStaffsAsync(string openID, object userState) {
            if ((this.GetEnabledStaffsOperationCompleted == null)) {
                this.GetEnabledStaffsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEnabledStaffsOperationCompleted);
            }
            this.InvokeAsync("GetEnabledStaffs", new object[] {
                        openID}, this.GetEnabledStaffsOperationCompleted, userState);
        }
        
        private void OnGetEnabledStaffsOperationCompleted(object arg) {
            if ((this.GetEnabledStaffsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEnabledStaffsCompleted(this, new GetEnabledStaffsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetAssociatedAccount", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountExpandoProperty GetAssociatedAccount(string staffOpenID) {
            object[] results = this.Invoke("GetAssociatedAccount", new object[] {
                        staffOpenID});
            return ((AccountExpandoProperty)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssociatedAccountAsync(string staffOpenID) {
            this.GetAssociatedAccountAsync(staffOpenID, null);
        }
        
        /// <remarks/>
        public void GetAssociatedAccountAsync(string staffOpenID, object userState) {
            if ((this.GetAssociatedAccountOperationCompleted == null)) {
                this.GetAssociatedAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssociatedAccountOperationCompleted);
            }
            this.InvokeAsync("GetAssociatedAccount", new object[] {
                        staffOpenID}, this.GetAssociatedAccountOperationCompleted, userState);
        }
        
        private void OnGetAssociatedAccountOperationCompleted(object arg) {
            if ((this.GetAssociatedAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssociatedAccountCompleted(this, new GetAssociatedAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class Organization : OrganizationObjectBase {
        
        private bool isVirtualField;
        
        /// <remarks/>
        public bool IsVirtual {
            get {
                return this.isVirtualField;
            }
            set {
                this.isVirtualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Staff))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Position))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class OrganizationObjectBase : DbHelper {
        
        private System.Guid uniqueIDField;
        
        private string nameField;
        
        private string openIDField;
        
        private System.Guid parentIDField;
        
        private OrganizationObjectCategory categoryField;
        
        private string virtualNameField;
        
        private string virtualPathField;
        
        private bool logicalRemovedStateField;
        
        private bool enabledField;
        
        private bool visibleField;
        
        private string descriptionField;
        
        /// <remarks/>
        public System.Guid UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string OpenID {
            get {
                return this.openIDField;
            }
            set {
                this.openIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        public OrganizationObjectCategory Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string VirtualName {
            get {
                return this.virtualNameField;
            }
            set {
                this.virtualNameField = value;
            }
        }
        
        /// <remarks/>
        public string VirtualPath {
            get {
                return this.virtualPathField;
            }
            set {
                this.virtualPathField = value;
            }
        }
        
        /// <remarks/>
        public bool LogicalRemovedState {
            get {
                return this.logicalRemovedStateField;
            }
            set {
                this.logicalRemovedStateField = value;
            }
        }
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public enum OrganizationObjectCategory {
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        VirtualOrganization,
        
        /// <remarks/>
        Position,
        
        /// <remarks/>
        Staff,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountExpandoProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterDeclaration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCredentialsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceRegion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Staff))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Position))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class DbHelper {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountExpandoProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class AccountBase : DbHelper {
        
        private System.Guid staffIDField;
        
        private string staffOpenIDField;
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Guid uniqueIDField;
        
        /// <remarks/>
        public System.Guid StaffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        public string StaffOpenID {
            get {
                return this.staffOpenIDField;
            }
            set {
                this.staffOpenIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class AccountExpandoProperty : AccountBase {
        
        private int expirationPolicyLengthField;
        
        private ExpirationPolicy policyField;
        
        private bool isLockedField;
        
        /// <remarks/>
        public int ExpirationPolicyLength {
            get {
                return this.expirationPolicyLengthField;
            }
            set {
                this.expirationPolicyLengthField = value;
            }
        }
        
        /// <remarks/>
        public ExpirationPolicy Policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public enum ExpirationPolicy {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        MonthPolicy,
        
        /// <remarks/>
        DayPolicy,
        
        /// <remarks/>
        WeekPolicy,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCredentialsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceRegion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public abstract partial class ParameterDeclaration : DbHelper {
        
        private System.Guid uniqueIDField;
        
        private string valueField;
        
        private string openIDField;
        
        private bool enabledField;
        
        /// <remarks/>
        public System.Guid UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string OpenID {
            get {
                return this.openIDField;
            }
            set {
                this.openIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class UserCredentialsType : ParameterDeclaration {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class PlaceRegion : ParameterDeclaration {
        
        private System.Guid parentIDField;
        
        /// <remarks/>
        public System.Guid ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class Staff : OrganizationObjectBase {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private System.Guid firstPositionIDField;
        
        private Gender genderField;
        
        private System.DateTime birthDateField;
        
        private PlaceRegion birthPlaceField;
        
        private string residentialAddressField;
        
        private UserCredentialsType userCredentialsTypeField;
        
        private string userCredentialsNOField;
        
        private System.Guid firstOrganizationIDField;
        
        private string officePhoneNOField;
        
        private string mobilePhoneNOField;
        
        private string emailAddressField;
        
        private System.DateTime entryDateField;
        
        private bool isProbationField;
        
        private int probationLengthField;
        
        private bool autoBecomeFullMemberField;
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid FirstPositionID {
            get {
                return this.firstPositionIDField;
            }
            set {
                this.firstPositionIDField = value;
            }
        }
        
        /// <remarks/>
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public PlaceRegion BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string ResidentialAddress {
            get {
                return this.residentialAddressField;
            }
            set {
                this.residentialAddressField = value;
            }
        }
        
        /// <remarks/>
        public UserCredentialsType UserCredentialsType {
            get {
                return this.userCredentialsTypeField;
            }
            set {
                this.userCredentialsTypeField = value;
            }
        }
        
        /// <remarks/>
        public string UserCredentialsNO {
            get {
                return this.userCredentialsNOField;
            }
            set {
                this.userCredentialsNOField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid FirstOrganizationID {
            get {
                return this.firstOrganizationIDField;
            }
            set {
                this.firstOrganizationIDField = value;
            }
        }
        
        /// <remarks/>
        public string OfficePhoneNO {
            get {
                return this.officePhoneNOField;
            }
            set {
                this.officePhoneNOField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNO {
            get {
                return this.mobilePhoneNOField;
            }
            set {
                this.mobilePhoneNOField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsProbation {
            get {
                return this.isProbationField;
            }
            set {
                this.isProbationField = value;
            }
        }
        
        /// <remarks/>
        public int ProbationLength {
            get {
                return this.probationLengthField;
            }
            set {
                this.probationLengthField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoBecomeFullMember {
            get {
                return this.autoBecomeFullMemberField;
            }
            set {
                this.autoBecomeFullMemberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public enum Gender {
        
        /// <remarks/>
        Man,
        
        /// <remarks/>
        Woman,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class Position : OrganizationObjectBase {
        
        private System.Guid organizationIDField;
        
        /// <remarks/>
        public System.Guid OrganizationID {
            get {
                return this.organizationIDField;
            }
            set {
                this.organizationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRootOrganizationCompletedEventHandler(object sender, GetRootOrganizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRootOrganizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRootOrganizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Organization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Organization)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateOrganizationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSubOrganizationsCompletedEventHandler(object sender, GetSubOrganizationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubOrganizationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubOrganizationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrganizationObjectBase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrganizationObjectBase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateOrganizationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreatePositionCompletedEventHandler(object sender, CreatePositionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPositionCollectionExcludeSpecifiedCompletedEventHandler(object sender, GetPositionCollectionExcludeSpecifiedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionCollectionExcludeSpecifiedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPositionCollectionExcludeSpecifiedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Position[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Position[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdatePositionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateStaffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetEnabledStaffsCompletedEventHandler(object sender, GetEnabledStaffsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEnabledStaffsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEnabledStaffsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Staff[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Staff[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAssociatedAccountCompletedEventHandler(object sender, GetAssociatedAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssociatedAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssociatedAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountExpandoProperty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountExpandoProperty)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591