--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期五, 08 八月, 2014 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 


--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PassExpirationPolicy_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PassExpirationPolicy DROP CONSTRAINT FK_PassExpirationPolicy_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_AccountExpirationPolicy_PassExpirationPolicy') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.AccountExpirationPolicy DROP CONSTRAINT FK_AccountExpirationPolicy_PassExpirationPolicy
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_AccountExpirationPolicy_Account') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.AccountExpirationPolicy DROP CONSTRAINT FK_AccountExpirationPolicy_Account
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_RoleSetting_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.RoleSetting DROP CONSTRAINT FK_RoleSetting_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_RoleSetting_Role') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.RoleSetting DROP CONSTRAINT FK_RoleSetting_Role
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_RoleSetting_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.RoleSetting DROP CONSTRAINT FK_RoleSetting_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PermissionRoleSetting_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PermissionRoleSetting DROP CONSTRAINT FK_PermissionRoleSetting_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PermissionRoleSetting_Permission') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PermissionRoleSetting DROP CONSTRAINT FK_PermissionRoleSetting_Permission
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PermissionRoleSetting_Role') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PermissionRoleSetting DROP CONSTRAINT FK_PermissionRoleSetting_Role
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PermissionOrgSetting_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PermissionOrgSetting DROP CONSTRAINT FK_PermissionOrgSetting_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PermissionOrgSetting_Permission') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PermissionOrgSetting DROP CONSTRAINT FK_PermissionOrgSetting_Permission
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PermissionOrgSetting_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PermissionOrgSetting DROP CONSTRAINT FK_PermissionOrgSetting_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Permission_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Permission DROP CONSTRAINT FK_Permission_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Permission_Subsystem') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Permission DROP CONSTRAINT FK_Permission_Subsystem
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Subsystem_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Subsystem DROP CONSTRAINT FK_Subsystem_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SubsysAdministrator_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SubsysAdministrator DROP CONSTRAINT FK_SubsysAdministrator_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SubsysAdministrator_Subsystem') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SubsysAdministrator DROP CONSTRAINT FK_SubsysAdministrator_Subsystem
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_StaffAccount_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.StaffAccount DROP CONSTRAINT FK_StaffAccount_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_StaffAccount_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.StaffAccount DROP CONSTRAINT FK_StaffAccount_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_StaffAccount_PredefinedCode') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.StaffAccount DROP CONSTRAINT FK_StaffAccount_PredefinedCode
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Staff_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Staff DROP CONSTRAINT FK_Staff_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Staff_OrganizationObject_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Staff DROP CONSTRAINT FK_Staff_OrganizationObject_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Staff_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Staff DROP CONSTRAINT FK_Staff_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Staff_GlobalRegion') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Staff DROP CONSTRAINT FK_Staff_GlobalRegion
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Staff_CredentialsType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Staff DROP CONSTRAINT FK_Staff_CredentialsType
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Staff_OrganizationObject_03') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Staff DROP CONSTRAINT FK_Staff_OrganizationObject_03
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SqlLogTrace_BaseLogTrace') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SqlLogTrace DROP CONSTRAINT FK_SqlLogTrace_BaseLogTrace
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SqlLogTrace_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SqlLogTrace DROP CONSTRAINT FK_SqlLogTrace_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SignInToken_SignInAction') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SignInToken DROP CONSTRAINT FK_SignInToken_SignInAction
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SignInToken_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SignInToken DROP CONSTRAINT FK_SignInToken_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SignInLogTrace_BaseLogTrace') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SignInLogTrace DROP CONSTRAINT FK_SignInLogTrace_BaseLogTrace
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SignInLogTrace_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SignInLogTrace DROP CONSTRAINT FK_SignInLogTrace_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SignInAction_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SignInAction DROP CONSTRAINT FK_SignInAction_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_SignInAction_Account') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.SignInAction DROP CONSTRAINT FK_SignInAction_Account
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Role_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Role DROP CONSTRAINT FK_Role_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Role_Subsystem') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Role DROP CONSTRAINT FK_Role_Subsystem
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PositionRelation_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PositionRelation DROP CONSTRAINT FK_PositionRelation_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PositionRelation_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PositionRelation DROP CONSTRAINT FK_PositionRelation_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_PositionRelation_OrganizationObject_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.PositionRelation DROP CONSTRAINT FK_PositionRelation_OrganizationObject_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Position_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Position DROP CONSTRAINT FK_Position_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Position_OrganizationObject_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Position DROP CONSTRAINT FK_Position_OrganizationObject_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_ParttimeRelation_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.ParttimeRelation DROP CONSTRAINT FK_ParttimeRelation_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_ParttimeRelation_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.ParttimeRelation DROP CONSTRAINT FK_ParttimeRelation_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_ParttimeRelation_OrganizationObject_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.ParttimeRelation DROP CONSTRAINT FK_ParttimeRelation_OrganizationObject_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Organization_OrganizationObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Organization DROP CONSTRAINT FK_Organization_OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Organization_OrganizationObject_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Organization DROP CONSTRAINT FK_Organization_OrganizationObject_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Organization_OrganizationObject_03') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Organization DROP CONSTRAINT FK_Organization_OrganizationObject_03
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_BaseLogTrace_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.BaseLogTrace DROP CONSTRAINT FK_BaseLogTrace_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_BaseLogTrace_Account') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.BaseLogTrace DROP CONSTRAINT FK_BaseLogTrace_Account
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Administrator_Account') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Administrator DROP CONSTRAINT FK_Administrator_Account
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Administrator_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Administrator DROP CONSTRAINT FK_Administrator_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.FK_Account_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Secure.Account DROP CONSTRAINT FK_Account_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_PredefinedCode_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.PredefinedCode DROP CONSTRAINT FK_PredefinedCode_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_PredefinedCode_ObjectBase_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.PredefinedCode DROP CONSTRAINT FK_PredefinedCode_ObjectBase_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_PredefinedCode_ApplicationBlock') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.PredefinedCode DROP CONSTRAINT FK_PredefinedCode_ApplicationBlock
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_HotfixRelease_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.HotfixRelease DROP CONSTRAINT FK_HotfixRelease_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_HotfixRelease_ApplicationBlock') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.HotfixRelease DROP CONSTRAINT FK_HotfixRelease_ApplicationBlock
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_HotfixRelease_PredefinedCode') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.HotfixRelease DROP CONSTRAINT FK_HotfixRelease_PredefinedCode
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_GlobalRegion_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.GlobalRegion DROP CONSTRAINT FK_GlobalRegion_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_FileStream_FileObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.FileStream DROP CONSTRAINT FK_FileStream_FileObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_FileObject_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.FileObject DROP CONSTRAINT FK_FileObject_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_FileMapRelation_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.FileMapRelation DROP CONSTRAINT FK_FileMapRelation_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_FileMapRelation_FileObject') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.FileMapRelation DROP CONSTRAINT FK_FileMapRelation_FileObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_CredentialsType_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.CredentialsType DROP CONSTRAINT FK_CredentialsType_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_ApplicationBlock_ObjectBase') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.ApplicationBlock DROP CONSTRAINT FK_ApplicationBlock_ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FK_ApplicationBlock_ObjectBase_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Basic.ApplicationBlock DROP CONSTRAINT FK_ApplicationBlock_ObjectBase_02
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.PassExpirationPolicy') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.PassExpirationPolicy
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.AccountExpirationPolicy') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.AccountExpirationPolicy
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.RoleSetting') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.RoleSetting
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.PermissionRoleSetting') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.PermissionRoleSetting
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.PermissionOrgSetting') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.PermissionOrgSetting
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Permission') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Permission
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Subsystem') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Subsystem
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.SubsysAdministrator') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.SubsysAdministrator
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.StaffAccount') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.StaffAccount
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Staff') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Staff
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.SqlLogTrace') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.SqlLogTrace
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.SignInToken') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.SignInToken
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.SignInLogTrace') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.SignInLogTrace
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.SignInAction') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.SignInAction
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Role') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Role
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.PositionRelation') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.PositionRelation
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Position') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Position
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.ParttimeRelation') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.ParttimeRelation
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.OrganizationObject') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.OrganizationObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Organization') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Organization
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.BaseLogTrace') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.BaseLogTrace
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Administrator') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Administrator
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Secure.Account') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Secure.Account
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.PredefinedCode') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.PredefinedCode
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.ObjectBase') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.ObjectBase
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.HotfixRelease') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.HotfixRelease
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.GlobalRegion') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.GlobalRegion
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FileStream') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.FileStream
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FileObject') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.FileObject
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.FileMapRelation') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.FileMapRelation
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.CredentialsType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.CredentialsType
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Basic.ApplicationBlock') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Basic.ApplicationBlock
;


--  Create Tables 
CREATE TABLE Secure.PassExpirationPolicy ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：策略唯一标识（关联到ObjectBase表）。 
	Description nvarchar(256) NOT NULL,    --  策略描述信息。 
	ExpirationUnit char(1) DEFAULT 'D' NOT NULL,    --  过期计算单位：N(无过期）；M（按月计算）；D（按日计算）；W（按周计算）。 
	ExpirationValue int DEFAULT 90 NOT NULL    --  过期值。 
)
;

CREATE TABLE Secure.AccountExpirationPolicy ( 
	AccountID uniqueidentifier NOT NULL,    --  PK&FK：账户标识（关联到Account表）。 
	PolicyID uniqueidentifier NOT NULL    --  PK&FK：策略标识（关联到PassExpirationPolicy表）。 
)
;

CREATE TABLE Secure.RoleSetting ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：角色设置唯一标识（关联到ObjectBase表）。 
	RoleID uniqueidentifier NOT NULL,    --  FK：角色标识（关联到Role表）。 
	OrganizationID uniqueidentifier NOT NULL    --  FK：授权的组织机构对象标识（关联到OrganizationObject表）。 
)
;

CREATE TABLE Secure.PermissionRoleSetting ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：角色、权限设置关系唯一标识（关联到ObjectBase表）。 
	PermissionID uniqueidentifier NOT NULL,    --  FK：权限标识（关联到Permission表）。 
	RoleID uniqueidentifier    --  FK：角色标识（关联到Role表）。 
)
;

CREATE TABLE Secure.PermissionOrgSetting ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：设置关系唯一标识（关联到ObjectBase表）。 
	PermissionID uniqueidentifier NOT NULL,    --  FK：权限标识（关联到Permission表）。 
	OrganizationID uniqueidentifier NOT NULL    --  FK：被授权的组织机构对象标识（关联到OrganizationObject表）。 
)
;

CREATE TABLE Secure.Permission ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：权限唯一标识（关联到ObjectBase表）。 
	PermissionCode varchar(512) NOT NULL,    --  权限代码。 
	SysID uniqueidentifier NOT NULL    --  FK：子系统标识（关联到Subsystem表）。 
)
;

CREATE TABLE Secure.Subsystem ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：应用系统唯一标识（关联到ObjectBase表）。 
	SysName nvarchar(512) NOT NULL,    --  子系统名称。 
	SysCode varchar(256) NOT NULL,    --  子系统编码。 
	ParentSysID uniqueidentifier,    --  父系统标识。 
	InheritFromParent char(1) DEFAULT 'Y' NOT NULL    --  是否继承父应用所有属性：Y（是）；N（否）。 
)
;

CREATE TABLE Secure.SubsysAdministrator ( 
	StaffID uniqueidentifier NOT NULL,    --  PK&FK：人员对象标识（关联到OrganizationObject表）。 
	SysID uniqueidentifier NOT NULL    --  PK&FK：应用系统标识（关联到Subsystem表）。 
)
;

CREATE TABLE Secure.StaffAccount ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：人员帐户表（关联到Account）。 
	StaffID uniqueidentifier NOT NULL,    --  FK：人员标识（关联到OrganizationObject表）。 
	IsLocked char(1) DEFAULT 'N' NOT NULL,    --  账户是否被锁定：Y（是）；N（否）。 
	LockReason uniqueidentifier NOT NULL,    --  FK：锁定原因代码标识（关联到PredefinedCode表）。 
	LockedTime datetime DEFAULT NULL,    --  锁定时间。 
	UnlockTime bigint DEFAULT NULL    --  解锁时间。 
)
;

CREATE TABLE Secure.Staff ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：人员对象唯一标识（关联到OrganizationObject和ObjectBase表）。 
	LastName nvarchar(64) DEFAULT NULL,    --  姓氏 
	FirstName nvarchar(64) DEFAULT NULL,    --  名字。 
	OrganizationID uniqueidentifier NOT NULL,    --  FK：人员的主要任职组织标识（关联到OrganizationObject表）。 
	Gender char(1) DEFAULT 'M' NOT NULL,    --  人员性别：M（男）；W（女）。 
	BirthDate datetime DEFAULT NULL,    --  人员出生日期。 
	BirthPlaceID uniqueidentifier,    --  FK：出生地标识（关联到GlobalRegion表）。 
	ResidenceAddress nvarchar(max) DEFAULT NULL,    --  居住地址。 
	CredentialsTypeID uniqueidentifier,    --  FK：证件类型标识（关联到CredentialsType表）。 
	CredentialsNO varchar(128) DEFAULT NULL,    --  证件编号。 
	PositionID uniqueidentifier NOT NULL,    --  FK：主要职位ID（关联到OrganizationObject表）。 
	OfficePhoneNO varchar(16) DEFAULT NULL,    --  办公电话号码。 
	MobileNO varchar(16) DEFAULT NULL,    --  移动电话号码。 
	EmailAddress varchar(512) DEFAULT NULL,    --  电子邮件地址。 
	InductionDate datetime DEFAULT Getdate() NOT NULL,    --  入职日期。 
	IsProbationary char(1) DEFAULT 'N' NOT NULL,    --  是否为试用期员工：Y（是）；N（否）。 
	ProbationLength int DEFAULT 3 NOT NULL,    --  试用期长度（单位：月）。 
	AutoRegularized char(1) DEFAULT 'Y' NOT NULL    --  是否自动转正：Y（是）；N（否）。 
)
;

CREATE TABLE Secure.SqlLogTrace ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：日志行为唯一标识（关联到BaseLogTrace及ObjectBase表）。 
	Command varchar(max) NOT NULL,    --  SQL命令文本。 
	CommandType char(1) DEFAULT 'T' NOT NULL    --  命令类型：T（SQL命令串）；S（存储过程）；F（函数） 
)
;

CREATE TABLE Secure.SignInToken ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：登录票据唯一标识（关联到ObjectBase表）。 
	ActionID uniqueidentifier NOT NULL,    --  FK：登录动作标识（关联到SignInAction表）。 
	Token varchar(max) NOT NULL,    --  登录令牌字符串。 
	ExpiredTime datetime DEFAULT Getdate() NOT NULL    --  登录令牌失效时间。 
)
;

CREATE TABLE Secure.SignInLogTrace ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：日志行为唯一标识（关联到BaseLogTrace及ObjectBase表）。 
	IOFlag char(1) DEFAULT 'I' NOT NULL    --  登录、登出标记：I（登录）；O（登出）。 
)
;

CREATE TABLE Secure.SignInAction ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：登录动作唯一标识（关联到ObjectBase表）。 
	ClientIP varchar(64) DEFAULT NULL,    --  客户端IP地址。 
	HostName varchar(256) DEFAULT NULL,    --  主机名称。 
	Platform int DEFAULT 1 NOT NULL,    --  平台类型：1：PC；2：WP移动设备；3：Android移动设备；4：iOS移动设备；5：Firefox OS移动设备；6：Windows Mobile平台移动设备；7：塞班移动设备；8：MeeGo移动设备；9：黑莓移动设备；-1：未知类型的移动设备。 
	IsSucceed char(1) DEFAULT 'Y' NOT NULL,    --  是否成功：Y：（成功的）；N（失败的）。 
	FailedReasonCodeID uniqueidentifier DEFAULT NULL,    --  FK：失败原因代码（关联到PredefinedCode表）。 
	AccountID uniqueidentifier DEFAULT NULL,    --  FK：登录时所用的账户唯一标识（关联到Account表）。如果为NULL，则表示不是已知的账户。 
	UnknownUserID varchar(max) DEFAULT NULL    --  如果AccountID为NULL，则此字段保存错误的账户名称。 
)
;

CREATE TABLE Secure.Role ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：角色唯一标识（关联到ObjectBase表）。 
	RoleName nvarchar(512) NOT NULL,    --  角色名称。 
	RoleCode varchar(256) NOT NULL,    --  角色代码。 
	SysID uniqueidentifier NOT NULL    --  FK：子系统标识（关联到Subsystem表）。 
)
;

CREATE TABLE Secure.PositionRelation ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：汇报关系唯一标识（关联到ObjectBase表）。 
	SuperiorID uniqueidentifier NOT NULL,    --  FK：上一级职位标识（关联到OrganizationObject表）。 
	CurrentID uniqueidentifier NOT NULL    --  FK：当前职位标识（关联到OrganizationObject表）。 
)
;

CREATE TABLE Secure.Position ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：职位信息唯一标识（关联到OrganizationObject表）。 
	OrganizationID uniqueidentifier NOT NULL    --  FK：组织标识（关联到OrganizationObject表）。 
)
;

CREATE TABLE Secure.ParttimeRelation ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：兼职关系唯一标识（关联到ObjectBase表）。 
	StaffID uniqueidentifier NOT NULL,    --  FK：人员标识（关联到OrganizationObject表）。 
	PositionID uniqueidentifier NOT NULL    --  FK：兼职职位标识（关联到OrganizationObject表）。 
)
;

CREATE TABLE Secure.OrganizationObject ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：组织机构对象唯一标识（关联到ObjectBase表）。 
	ObjectName nvarchar(512) NOT NULL,    --  组织机构对象名称。 
	ParentObjectID uniqueidentifier DEFAULT NULL,    --  父组织机构对象ID。 
	Category int DEFAULT 1 NOT NULL,    --  组织机构对象类别：1：组织；2：人员组；3：职位；4：人员。 
	SortID int DEFAULT 0 NOT NULL,    --  排序标识。 
	VirtualName nvarchar(1024) NOT NULL    --  对象虚名称。 
)
;

CREATE TABLE Secure.Organization ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：组织唯一标识（关联到OrganizationObject表）。 
	PrincipalStaffID uniqueidentifier DEFAULT NULL,    --  FK：此组织的主要负责人标识（关联到OrganizationObject表）。 
	PrincipalPositionID uniqueidentifier DEFAULT NULL    --  FK：主要负责的职位标识（关联到OrganizationObject表）。 
)
;

CREATE TABLE Secure.BaseLogTrace ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：日志行为唯一标识（关联到ObjectBase表）。 
	MethodName varchar(512) DEFAULT 'ctor' NOT NULL,    --  调用的方法名称。 
	TypeName varchar(max) NOT NULL,    --  包含方法的类型名称。 
	Version varchar(36) DEFAULT '1.0' NOT NULL,    --  版本号。 
	CallAccountID uniqueidentifier    --  FK：调用者标识（关联到Account表）。 
)
;

CREATE TABLE Secure.Administrator ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：系统管理员唯一标识（关联到Account、ObjectBase表）。 
	IsDefault char(1) DEFAULT 'N' NOT NULL,    --  是否为默认系统管理员账户：Y（是）；N（否）。默认的系统管理员不可删除。 
	WindowsIntergrated char(1) DEFAULT 'Y' NOT NULL    --  是否集成Windows账户：Y（是）；N（否）。 
)
;

CREATE TABLE Secure.Account ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK：系统账户唯一标识（关联到ObjectBase表）。 
	UserID varchar(512) DEFAULT 'Administrator' NOT NULL,    --  账户。 
	Passphrase varchar(max) DEFAULT NULL,    --  口令。 
	EmptyPass char(1) DEFAULT 'N' NOT NULL    --  是否为空密码：Y（是）、N（否）。 
)
;

CREATE TABLE Basic.PredefinedCode ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK & FK：系统预定义代码唯一标识（关联到ObjectBase表）。 
	BlockID uniqueidentifier,    --  FK：应用模块唯一标识（关联到ObjectBase、ApplicationBlock表）。 
	Code varchar(64) DEFAULT 'ERROR_00000001' NOT NULL    --  代码。 
)
;

CREATE TABLE Basic.ObjectBase ( 
	ObjectID uniqueidentifier DEFAULT NewId() NOT NULL,    --  PK：对象唯一标识。 
	IsRemoved char(1) DEFAULT 'N' NOT NULL,    --  是否已经被逻辑删除：Y（是）；N（否）。 
	Enabled char(1) DEFAULT 'Y' NOT NULL,    --  是否被启用：Y（是）；N（否）。 
	Visible char(1) DEFAULT 'Y' NOT NULL,    --  是否可见：Y（可见的）；N（隐藏的）。 
	OpenID varchar(256) NOT NULL,    --  对外公开的唯一标识。 
	IsCreatedTime datetime DEFAULT Getdate() NOT NULL,    --  对象被创建的时间。 
	LastModifiedTime datetime DEFAULT NULL,    --  最后一次被修改的时间。 
	IsModifiedTimes int DEFAULT 0 NOT NULL,    --  对象被修改的次数。 
	Comments nvarchar(max) DEFAULT NULL    --  对象的备注信息。 
)
;

CREATE TABLE Basic.HotfixRelease ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK & FK：更新补丁唯一标识（关联到ObjectBase表）。 
	CodeID uniqueidentifier NOT NULL,    --  FK：更新代码ID（关联到PredefinedCode表）。 
	BlockID uniqueidentifier NOT NULL,    --  FK：需要更新的模块标识（关联到ApplicationBlock表）。 
	Version varchar(16) DEFAULT '1.0' NOT NULL,    --  更新补丁的版本号。 
	FeatureSummary nvarchar(256) DEFAULT NULL,    --  功能概述。 
	ReleaseDate datetime NOT NULL,    --  发布日期。 
	IsImportant char(1) DEFAULT 'Y' NOT NULL    --  是否为重要更新：Y（是）；N（否）。 
)
;

CREATE TABLE Basic.GlobalRegion ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：区域唯一标识（关联到ObjectBase表）。 
	RegionName nvarchar(256) DEFAULT '中华人民共和国' NOT NULL,    --  区域名称。 
	ParentRegionID uniqueidentifier DEFAULT NULL    --  父区域标识。 
)
;

CREATE TABLE Basic.FileStream ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK & FK：文件对象唯一标识（关联到FileObject表）。 
	Stream varbinary(max) DEFAULT NULL    --  文件流数据。 
)
;

CREATE TABLE Basic.FileObject ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK & FK：文件对象唯一标识（关联到ObjectBase表）。 
	RawName nvarchar(512) NOT NULL,    --  文件原始名称。 
	ExtensionName varchar(16) DEFAULT NULL,    --  文件扩展名。 
	MimeType varchar(64) NOT NULL,    --  文件类型对应的Http Mime类型。 
	FileSize bigint DEFAULT 0 NOT NULL,    --  文件长度。 
	SaveToDB char(1) DEFAULT 'N' NOT NULL,    --  是否保存到数据库：Y（以保存到数据库）；N（未保存到数据库）。 
	SaveToDisk char(1) DEFAULT 'Y' NOT NULL,    --  是否保存到服务器物理硬盘中：Y（是）；N（否）。 
	PhysicalPath nvarchar(2048) DEFAULT NULL    --  文件的物理路径。 
)
;

CREATE TABLE Basic.FileMapRelation ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：关系唯一标识（关联到ObjectBase表）。 
	FileID uniqueidentifier NOT NULL,    --  FK：文件对象标识（关联到FileObject表）。 
	AssociatedObjectID uniqueidentifier NOT NULL    --  FK：关联的对象唯一标识。 
)
;

CREATE TABLE Basic.CredentialsType ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：证件类型唯一标识（关联到ObjectBase表）。 
	TypeName nvarchar(256) NOT NULL    --  证件类型名称。 
)
;

CREATE TABLE Basic.ApplicationBlock ( 
	UniqueID uniqueidentifier NOT NULL,    --  PK&FK：系统模块唯一标识（关联到ObjectBase表）。 
	BlockName nvarchar(128) DEFAULT '基础数据模块' NOT NULL,    --  应用模块名称（简体中文）。 
	ParentBlockID uniqueidentifier DEFAULT NULL,    --  上级模块ID（关联到ApplicationBlock、ObjectBase表）。 
	Code varchar(128) DEFAULT 'BASIC' NOT NULL,    --  应用模块代码。 
	XExpando xml DEFAULT NULL    --  扩展信息。 
)
;


--  Create Indexes 
CREATE INDEX IXFK_PassExpirationPolicy_ObjectBase
	ON Secure.PassExpirationPolicy (UniqueID ASC)
;

CREATE INDEX IXFK_AccountExpirationPolicy_PassExpirationPolicy
	ON Secure.AccountExpirationPolicy (PolicyID ASC)
;

CREATE INDEX IXFK_AccountExpirationPolicy_Account
	ON Secure.AccountExpirationPolicy (AccountID ASC)
;

CREATE INDEX IXFK_RoleSetting_ObjectBase
	ON Secure.RoleSetting (UniqueID ASC)
;

CREATE INDEX IXFK_RoleSetting_Role
	ON Secure.RoleSetting (RoleID ASC)
;

CREATE INDEX IXFK_RoleSetting_OrganizationObject
	ON Secure.RoleSetting (OrganizationID ASC)
;

CREATE INDEX IXFK_PermissionRoleSetting_ObjectBase
	ON Secure.PermissionRoleSetting (UniqueID ASC)
;

CREATE INDEX IXFK_PermissionRoleSetting_Permission
	ON Secure.PermissionRoleSetting (PermissionID ASC)
;

CREATE INDEX IXFK_PermissionRoleSetting_Role
	ON Secure.PermissionRoleSetting (RoleID ASC)
;

CREATE INDEX IXFK_PermissionOrgSetting_ObjectBase
	ON Secure.PermissionOrgSetting (UniqueID ASC)
;

CREATE INDEX IXFK_PermissionOrgSetting_Permission
	ON Secure.PermissionOrgSetting (PermissionID ASC)
;

CREATE INDEX IXFK_PermissionOrgSetting_OrganizationObject
	ON Secure.PermissionOrgSetting (OrganizationID ASC)
;

CREATE INDEX IXFK_Permission_ObjectBase
	ON Secure.Permission (UniqueID ASC)
;

CREATE INDEX IXFK_Permission_Subsystem
	ON Secure.Permission (SysID ASC)
;

ALTER TABLE Secure.Subsystem
	ADD CONSTRAINT UQ_Subsystem_SysName UNIQUE (SysName)
;

ALTER TABLE Secure.Subsystem
	ADD CONSTRAINT UQ_Subsystem_SysCode UNIQUE (SysCode)
;

CREATE INDEX IXFK_Subsystem_ObjectBase
	ON Secure.Subsystem (UniqueID ASC)
;

CREATE INDEX IXFK_SubsysAdministrator_OrganizationObject
	ON Secure.SubsysAdministrator (StaffID ASC)
;

CREATE INDEX IXFK_SubsysAdministrator_Subsystem
	ON Secure.SubsysAdministrator (SysID ASC)
;

CREATE INDEX IXFK_StaffAccount_ObjectBase
	ON Secure.StaffAccount (UniqueID ASC)
;

CREATE INDEX IXFK_StaffAccount_OrganizationObject
	ON Secure.StaffAccount (StaffID ASC)
;

CREATE INDEX IXFK_StaffAccount_PredefinedCode
	ON Secure.StaffAccount (LockReason ASC)
;

CREATE INDEX IXFK_Staff_OrganizationObject
	ON Secure.Staff (UniqueID ASC)
;

CREATE INDEX IXFK_Staff_OrganizationObject_02
	ON Secure.Staff (OrganizationID ASC)
;

CREATE INDEX IXFK_Staff_GlobalRegion
	ON Secure.Staff (BirthPlaceID ASC)
;

CREATE INDEX IXFK_Staff_CredentialsType
	ON Secure.Staff (CredentialsTypeID ASC)
;

CREATE INDEX IXFK_Staff_OrganizationObject_03
	ON Secure.Staff (PositionID ASC)
;

CREATE INDEX IXFK_SqlLogTrace_BaseLogTrace
	ON Secure.SqlLogTrace (UniqueID ASC)
;

CREATE INDEX IXFK_SignInToken_SignInAction
	ON Secure.SignInToken (ActionID ASC)
;

CREATE INDEX IXFK_SignInToken_ObjectBase
	ON Secure.SignInToken (UniqueID ASC)
;

CREATE INDEX IXFK_SignInLogTrace_BaseLogTrace
	ON Secure.SignInLogTrace (UniqueID ASC)
;

CREATE INDEX IXFK_SignInAction_ObjectBase
	ON Secure.SignInAction (UniqueID ASC)
;

CREATE INDEX IXFK_SignInAction_Account
	ON Secure.SignInAction (AccountID ASC)
;

CREATE INDEX IXFK_Role_ObjectBase
	ON Secure.Role (UniqueID ASC)
;

CREATE INDEX IXFK_Role_Subsystem
	ON Secure.Role (SysID ASC)
;

CREATE INDEX IXFK_PositionRelation_ObjectBase
	ON Secure.PositionRelation (UniqueID ASC)
;

CREATE INDEX IXFK_PositionRelation_OrganizationObject
	ON Secure.PositionRelation (SuperiorID ASC)
;

CREATE INDEX IXFK_PositionRelation_OrganizationObject_02
	ON Secure.PositionRelation (CurrentID ASC)
;

CREATE INDEX IXFK_Position_OrganizationObject
	ON Secure.Position (UniqueID ASC)
;

CREATE INDEX IXFK_Position_OrganizationObject_02
	ON Secure.Position (OrganizationID ASC)
;

CREATE INDEX IXFK_ParttimeRelation_ObjectBase
	ON Secure.ParttimeRelation (UniqueID ASC)
;

CREATE INDEX IXFK_ParttimeRelation_OrganizationObject
	ON Secure.ParttimeRelation (StaffID ASC)
;

CREATE INDEX IXFK_ParttimeRelation_OrganizationObject_02
	ON Secure.ParttimeRelation (PositionID ASC)
;

ALTER TABLE Secure.OrganizationObject
	ADD CONSTRAINT UQ_OrganizationObject_VirtualName UNIQUE (VirtualName)
;

CREATE INDEX IXFK_Organization_OrganizationObject
	ON Secure.Organization (UniqueID ASC)
;

CREATE INDEX IXFK_Organization_OrganizationObject_02
	ON Secure.Organization (PrincipalStaffID ASC)
;

CREATE INDEX IXFK_Organization_OrganizationObject_03
	ON Secure.Organization (PrincipalPositionID ASC)
;

CREATE INDEX IXFK_BaseLogTrace_Account
	ON Secure.BaseLogTrace (CallAccountID ASC)
;

CREATE INDEX IXFK_BaseLogTrace_ObjectBase
	ON Secure.BaseLogTrace (UniqueID ASC)
;

CREATE INDEX IXFK_Administrator_Account
	ON Secure.Administrator (UniqueID ASC)
;

ALTER TABLE Secure.Account
	ADD CONSTRAINT UQ_Account_Account UNIQUE (UserID)
;

CREATE INDEX IXFK_Account_ObjectBase
	ON Secure.Account (UniqueID ASC)
;

CREATE INDEX IXFK_PredefinedCode_ObjectBase
	ON Basic.PredefinedCode (UniqueID ASC)
;

CREATE INDEX IXFK_PredefinedCode_ObjectBase_02
	ON Basic.PredefinedCode (BlockID ASC)
;

CREATE INDEX IXFK_HotfixRelease_ObjectBase
	ON Basic.HotfixRelease (UniqueID ASC)
;

CREATE INDEX IXFK_HotfixRelease_ApplicationBlock
	ON Basic.HotfixRelease (BlockID ASC)
;

CREATE INDEX IXFK_HotfixRelease_PredefinedCode
	ON Basic.HotfixRelease (CodeID ASC)
;

CREATE INDEX IXFK_GlobalRegion_ObjectBase
	ON Basic.GlobalRegion (UniqueID ASC)
;

CREATE INDEX IXFK_FileStream_FileObject
	ON Basic.FileStream (UniqueID ASC)
;

CREATE INDEX IXFK_FileObject_ObjectBase
	ON Basic.FileObject (UniqueID ASC)
;

CREATE INDEX IXFK_FileMapRelation_ObjectBase
	ON Basic.FileMapRelation (UniqueID ASC)
;

CREATE INDEX IXFK_FileMapRelation_FileObject
	ON Basic.FileMapRelation (FileID ASC)
;

ALTER TABLE Basic.CredentialsType
	ADD CONSTRAINT UQ_CredentialsType_TypeName UNIQUE (TypeName)
;

CREATE INDEX IXFK_CredentialsType_ObjectBase
	ON Basic.CredentialsType (UniqueID ASC)
;

CREATE INDEX IXFK_ApplicationBlock_ObjectBase
	ON Basic.ApplicationBlock (UniqueID ASC)
;

ALTER TABLE Basic.ApplicationBlock
	ADD CONSTRAINT UQ_ApplicationBlock_BlockName UNIQUE (BlockName)
;

CREATE INDEX IXFK_ApplicationBlock_ObjectBase_02
	ON Basic.ApplicationBlock (ParentBlockID ASC)
;

ALTER TABLE Basic.ApplicationBlock
	ADD CONSTRAINT UQ_ApplicationBlock_Code UNIQUE (Code)
;

--  Create Primary Key Constraints 
ALTER TABLE Secure.PassExpirationPolicy ADD CONSTRAINT PK_PassExpirationPolicy 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.AccountExpirationPolicy ADD CONSTRAINT PK_AccountExpirationPolicy 
	PRIMARY KEY CLUSTERED (AccountID, PolicyID)
;

ALTER TABLE Secure.RoleSetting ADD CONSTRAINT PK_RoleSetting 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.PermissionRoleSetting ADD CONSTRAINT PK_PermissionRoleSetting 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.PermissionOrgSetting ADD CONSTRAINT PK_PermissionOrgSetting 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Permission ADD CONSTRAINT PK_Permission 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Subsystem ADD CONSTRAINT PK_Subsystem 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.SubsysAdministrator ADD CONSTRAINT PK_SubsysAdministrator 
	PRIMARY KEY CLUSTERED (StaffID, SysID)
;

ALTER TABLE Secure.StaffAccount ADD CONSTRAINT PK_StaffAccount 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT PK_Staff 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.SqlLogTrace ADD CONSTRAINT PK_SqlLogTrace 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.SignInToken ADD CONSTRAINT PK_SignInToken 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.SignInLogTrace ADD CONSTRAINT PK_SignInLogTrace 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.SignInAction ADD CONSTRAINT PK_SignInAction 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Role ADD CONSTRAINT PK_Role 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.PositionRelation ADD CONSTRAINT PK_PositionRelation 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Position ADD CONSTRAINT PK_Position 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.ParttimeRelation ADD CONSTRAINT PK_ParttimeRelation 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.OrganizationObject ADD CONSTRAINT PK_OrganizationObjectBase 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Organization ADD CONSTRAINT PK_Organization 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.BaseLogTrace ADD CONSTRAINT PK_BaseLog 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Administrator ADD CONSTRAINT PK_Administrator 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Secure.Account ADD CONSTRAINT PK_Account 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.PredefinedCode ADD CONSTRAINT PK_PredefinedCode 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.ObjectBase ADD CONSTRAINT PK_ObjectBase 
	PRIMARY KEY CLUSTERED (ObjectID)
;

ALTER TABLE Basic.HotfixRelease ADD CONSTRAINT PK_HotfixRelease 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.GlobalRegion ADD CONSTRAINT PK_GlobalRegion 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.FileStream ADD CONSTRAINT PK_FileStream 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.FileObject ADD CONSTRAINT PK_FileObject 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.FileMapRelation ADD CONSTRAINT PK_FileMapRelation 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.CredentialsType ADD CONSTRAINT PK_CredentialsType 
	PRIMARY KEY CLUSTERED (UniqueID)
;

ALTER TABLE Basic.ApplicationBlock ADD CONSTRAINT PK_ApplicationBlock 
	PRIMARY KEY CLUSTERED (UniqueID)
;



--  Create Foreign Key Constraints 
ALTER TABLE Secure.PassExpirationPolicy ADD CONSTRAINT FK_PassExpirationPolicy_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.AccountExpirationPolicy ADD CONSTRAINT FK_AccountExpirationPolicy_PassExpirationPolicy 
	FOREIGN KEY (PolicyID) REFERENCES Secure.PassExpirationPolicy (UniqueID)
;

ALTER TABLE Secure.AccountExpirationPolicy ADD CONSTRAINT FK_AccountExpirationPolicy_Account 
	FOREIGN KEY (AccountID) REFERENCES Secure.Account (UniqueID)
;

ALTER TABLE Secure.RoleSetting ADD CONSTRAINT FK_RoleSetting_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.RoleSetting ADD CONSTRAINT FK_RoleSetting_Role 
	FOREIGN KEY (RoleID) REFERENCES Secure.Role (UniqueID)
;

ALTER TABLE Secure.RoleSetting ADD CONSTRAINT FK_RoleSetting_OrganizationObject 
	FOREIGN KEY (OrganizationID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.PermissionRoleSetting ADD CONSTRAINT FK_PermissionRoleSetting_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.PermissionRoleSetting ADD CONSTRAINT FK_PermissionRoleSetting_Permission 
	FOREIGN KEY (PermissionID) REFERENCES Secure.Permission (UniqueID)
;

ALTER TABLE Secure.PermissionRoleSetting ADD CONSTRAINT FK_PermissionRoleSetting_Role 
	FOREIGN KEY (RoleID) REFERENCES Secure.Role (UniqueID)
;

ALTER TABLE Secure.PermissionOrgSetting ADD CONSTRAINT FK_PermissionOrgSetting_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.PermissionOrgSetting ADD CONSTRAINT FK_PermissionOrgSetting_Permission 
	FOREIGN KEY (PermissionID) REFERENCES Secure.Permission (UniqueID)
;

ALTER TABLE Secure.PermissionOrgSetting ADD CONSTRAINT FK_PermissionOrgSetting_OrganizationObject 
	FOREIGN KEY (OrganizationID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Permission ADD CONSTRAINT FK_Permission_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.Permission ADD CONSTRAINT FK_Permission_Subsystem 
	FOREIGN KEY (SysID) REFERENCES Secure.Subsystem (UniqueID)
;

ALTER TABLE Secure.Subsystem ADD CONSTRAINT FK_Subsystem_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.SubsysAdministrator ADD CONSTRAINT FK_SubsysAdministrator_OrganizationObject 
	FOREIGN KEY (StaffID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.SubsysAdministrator ADD CONSTRAINT FK_SubsysAdministrator_Subsystem 
	FOREIGN KEY (SysID) REFERENCES Secure.Subsystem (UniqueID)
;

ALTER TABLE Secure.StaffAccount ADD CONSTRAINT FK_StaffAccount_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.StaffAccount ADD CONSTRAINT FK_StaffAccount_OrganizationObject 
	FOREIGN KEY (StaffID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.StaffAccount ADD CONSTRAINT FK_StaffAccount_PredefinedCode 
	FOREIGN KEY (LockReason) REFERENCES Basic.PredefinedCode (UniqueID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT FK_Staff_OrganizationObject 
	FOREIGN KEY (UniqueID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT FK_Staff_OrganizationObject_02 
	FOREIGN KEY (OrganizationID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT FK_Staff_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT FK_Staff_GlobalRegion 
	FOREIGN KEY (BirthPlaceID) REFERENCES Basic.GlobalRegion (UniqueID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT FK_Staff_CredentialsType 
	FOREIGN KEY (CredentialsTypeID) REFERENCES Basic.CredentialsType (UniqueID)
;

ALTER TABLE Secure.Staff ADD CONSTRAINT FK_Staff_OrganizationObject_03 
	FOREIGN KEY (PositionID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.SqlLogTrace ADD CONSTRAINT FK_SqlLogTrace_BaseLogTrace 
	FOREIGN KEY (UniqueID) REFERENCES Secure.BaseLogTrace (UniqueID)
;

ALTER TABLE Secure.SqlLogTrace ADD CONSTRAINT FK_SqlLogTrace_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.SignInToken ADD CONSTRAINT FK_SignInToken_SignInAction 
	FOREIGN KEY (ActionID) REFERENCES Secure.SignInAction (UniqueID)
;

ALTER TABLE Secure.SignInToken ADD CONSTRAINT FK_SignInToken_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.SignInLogTrace ADD CONSTRAINT FK_SignInLogTrace_BaseLogTrace 
	FOREIGN KEY (UniqueID) REFERENCES Secure.BaseLogTrace (UniqueID)
;

ALTER TABLE Secure.SignInLogTrace ADD CONSTRAINT FK_SignInLogTrace_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.SignInAction ADD CONSTRAINT FK_SignInAction_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.SignInAction ADD CONSTRAINT FK_SignInAction_Account 
	FOREIGN KEY (AccountID) REFERENCES Secure.Account (UniqueID)
;

ALTER TABLE Secure.Role ADD CONSTRAINT FK_Role_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.Role ADD CONSTRAINT FK_Role_Subsystem 
	FOREIGN KEY (SysID) REFERENCES Secure.Subsystem (UniqueID)
;

ALTER TABLE Secure.PositionRelation ADD CONSTRAINT FK_PositionRelation_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.PositionRelation ADD CONSTRAINT FK_PositionRelation_OrganizationObject 
	FOREIGN KEY (SuperiorID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.PositionRelation ADD CONSTRAINT FK_PositionRelation_OrganizationObject_02 
	FOREIGN KEY (CurrentID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Position ADD CONSTRAINT FK_Position_OrganizationObject 
	FOREIGN KEY (UniqueID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Position ADD CONSTRAINT FK_Position_OrganizationObject_02 
	FOREIGN KEY (OrganizationID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.ParttimeRelation ADD CONSTRAINT FK_ParttimeRelation_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.ParttimeRelation ADD CONSTRAINT FK_ParttimeRelation_OrganizationObject 
	FOREIGN KEY (StaffID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.ParttimeRelation ADD CONSTRAINT FK_ParttimeRelation_OrganizationObject_02 
	FOREIGN KEY (PositionID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Organization ADD CONSTRAINT FK_Organization_OrganizationObject 
	FOREIGN KEY (UniqueID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Organization ADD CONSTRAINT FK_Organization_OrganizationObject_02 
	FOREIGN KEY (PrincipalStaffID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.Organization ADD CONSTRAINT FK_Organization_OrganizationObject_03 
	FOREIGN KEY (PrincipalPositionID) REFERENCES Secure.OrganizationObject (UniqueID)
;

ALTER TABLE Secure.BaseLogTrace ADD CONSTRAINT FK_BaseLogTrace_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.BaseLogTrace ADD CONSTRAINT FK_BaseLogTrace_Account 
	FOREIGN KEY (CallAccountID) REFERENCES Secure.Account (UniqueID)
;

ALTER TABLE Secure.Administrator ADD CONSTRAINT FK_Administrator_Account 
	FOREIGN KEY (UniqueID) REFERENCES Secure.Account (UniqueID)
;

ALTER TABLE Secure.Administrator ADD CONSTRAINT FK_Administrator_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Secure.Account ADD CONSTRAINT FK_Account_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.PredefinedCode ADD CONSTRAINT FK_PredefinedCode_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.PredefinedCode ADD CONSTRAINT FK_PredefinedCode_ObjectBase_02 
	FOREIGN KEY (BlockID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.PredefinedCode ADD CONSTRAINT FK_PredefinedCode_ApplicationBlock 
	FOREIGN KEY (BlockID) REFERENCES Basic.ApplicationBlock (UniqueID)
;

ALTER TABLE Basic.HotfixRelease ADD CONSTRAINT FK_HotfixRelease_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.HotfixRelease ADD CONSTRAINT FK_HotfixRelease_ApplicationBlock 
	FOREIGN KEY (BlockID) REFERENCES Basic.ApplicationBlock (UniqueID)
;

ALTER TABLE Basic.HotfixRelease ADD CONSTRAINT FK_HotfixRelease_PredefinedCode 
	FOREIGN KEY (CodeID) REFERENCES Basic.PredefinedCode (UniqueID)
;

ALTER TABLE Basic.GlobalRegion ADD CONSTRAINT FK_GlobalRegion_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.FileStream ADD CONSTRAINT FK_FileStream_FileObject 
	FOREIGN KEY (UniqueID) REFERENCES Basic.FileObject (UniqueID)
;

ALTER TABLE Basic.FileObject ADD CONSTRAINT FK_FileObject_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.FileMapRelation ADD CONSTRAINT FK_FileMapRelation_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.FileMapRelation ADD CONSTRAINT FK_FileMapRelation_FileObject 
	FOREIGN KEY (FileID) REFERENCES Basic.FileObject (UniqueID)
;

ALTER TABLE Basic.CredentialsType ADD CONSTRAINT FK_CredentialsType_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.ApplicationBlock ADD CONSTRAINT FK_ApplicationBlock_ObjectBase 
	FOREIGN KEY (UniqueID) REFERENCES Basic.ObjectBase (ObjectID)
;

ALTER TABLE Basic.ApplicationBlock ADD CONSTRAINT FK_ApplicationBlock_ObjectBase_02 
	FOREIGN KEY (ParentBlockID) REFERENCES Basic.ObjectBase (ObjectID)
;









EXEC sp_addextendedproperty 'MS_Description', '口令过期策略。', 'Schema', Secure, 'table', PassExpirationPolicy
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：策略唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', PassExpirationPolicy, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '策略描述信息。', 'Schema', Secure, 'table', PassExpirationPolicy, 'column', Description
;

EXEC sp_addextendedproperty 'MS_Description', '过期计算单位：N(无过期）；M（按月计算）；D（按日计算）；W（按周计算）。', 'Schema', Secure, 'table', PassExpirationPolicy, 'column', ExpirationUnit
;

EXEC sp_addextendedproperty 'MS_Description', '过期值。', 'Schema', Secure, 'table', PassExpirationPolicy, 'column', ExpirationValue
;

EXEC sp_addextendedproperty 'MS_Description', '账户过期策略。', 'Schema', Secure, 'table', AccountExpirationPolicy
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：账户标识（关联到Account表）。', 'Schema', Secure, 'table', AccountExpirationPolicy, 'column', AccountID
;

EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：策略标识（关联到PassExpirationPolicy表）。', 'Schema', Secure, 'table', AccountExpirationPolicy, 'column', PolicyID
;

EXEC sp_addextendedproperty 'MS_Description', '角色设置表。', 'Schema', Secure, 'table', RoleSetting
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：角色设置唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', RoleSetting, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：角色标识（关联到Role表）。', 'Schema', Secure, 'table', RoleSetting, 'column', RoleID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：授权的组织机构对象标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', RoleSetting, 'column', OrganizationID
;

EXEC sp_addextendedproperty 'MS_Description', '权限设置（关于角色）表。', 'Schema', Secure, 'table', PermissionRoleSetting
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：角色、权限设置关系唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', PermissionRoleSetting, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：权限标识（关联到Permission表）。', 'Schema', Secure, 'table', PermissionRoleSetting, 'column', PermissionID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：角色标识（关联到Role表）。', 'Schema', Secure, 'table', PermissionRoleSetting, 'column', RoleID
;

EXEC sp_addextendedproperty 'MS_Description', '权限设置表（关于组织机构）。', 'Schema', Secure, 'table', PermissionOrgSetting
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：设置关系唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', PermissionOrgSetting, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：权限标识（关联到Permission表）。', 'Schema', Secure, 'table', PermissionOrgSetting, 'column', PermissionID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：被授权的组织机构对象标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', PermissionOrgSetting, 'column', OrganizationID
;

EXEC sp_addextendedproperty 'MS_Description', '权限信息表。', 'Schema', Secure, 'table', Permission
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：权限唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', Permission, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '权限代码。', 'Schema', Secure, 'table', Permission, 'column', PermissionCode
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：子系统标识（关联到Subsystem表）。', 'Schema', Secure, 'table', Permission, 'column', SysID
;

EXEC sp_addextendedproperty 'MS_Description', '子系统定义表。', 'Schema', Secure, 'table', Subsystem
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：应用系统唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', Subsystem, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '子系统名称。', 'Schema', Secure, 'table', Subsystem, 'column', SysName
;

EXEC sp_addextendedproperty 'MS_Description', '子系统编码。', 'Schema', Secure, 'table', Subsystem, 'column', SysCode
;

EXEC sp_addextendedproperty 'MS_Description', '父系统标识。', 'Schema', Secure, 'table', Subsystem, 'column', ParentSysID
;

EXEC sp_addextendedproperty 'MS_Description', '是否继承父应用所有属性：Y（是）；N（否）。', 'Schema', Secure, 'table', Subsystem, 'column', InheritFromParent
;

EXEC sp_addextendedproperty 'MS_Description', '子系统管理员表。', 'Schema', Secure, 'table', SubsysAdministrator
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：人员对象标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', SubsysAdministrator, 'column', StaffID
;

EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：应用系统标识（关联到Subsystem表）。', 'Schema', Secure, 'table', SubsysAdministrator, 'column', SysID
;

EXEC sp_addextendedproperty 'MS_Description', '人员账户表。', 'Schema', Secure, 'table', StaffAccount
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：人员帐户表（关联到Account）。', 'Schema', Secure, 'table', StaffAccount, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：人员标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', StaffAccount, 'column', StaffID
;

EXEC sp_addextendedproperty 'MS_Description', '账户是否被锁定：Y（是）；N（否）。', 'Schema', Secure, 'table', StaffAccount, 'column', IsLocked
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：锁定原因代码标识（关联到PredefinedCode表）。', 'Schema', Secure, 'table', StaffAccount, 'column', LockReason
;

EXEC sp_addextendedproperty 'MS_Description', '锁定时间。', 'Schema', Secure, 'table', StaffAccount, 'column', LockedTime
;

EXEC sp_addextendedproperty 'MS_Description', '解锁时间。', 'Schema', Secure, 'table', StaffAccount, 'column', UnlockTime
;

EXEC sp_addextendedproperty 'MS_Description', '人员信息表。', 'Schema', Secure, 'table', Staff
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：人员对象唯一标识（关联到OrganizationObject和ObjectBase表）。', 'Schema', Secure, 'table', Staff, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '姓氏', 'Schema', Secure, 'table', Staff, 'column', LastName
;

EXEC sp_addextendedproperty 'MS_Description', '名字。', 'Schema', Secure, 'table', Staff, 'column', FirstName
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：人员的主要任职组织标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Staff, 'column', OrganizationID
;

EXEC sp_addextendedproperty 'MS_Description', '人员性别：M（男）；W（女）。', 'Schema', Secure, 'table', Staff, 'column', Gender
;

EXEC sp_addextendedproperty 'MS_Description', '人员出生日期。', 'Schema', Secure, 'table', Staff, 'column', BirthDate
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：出生地标识（关联到GlobalRegion表）。', 'Schema', Secure, 'table', Staff, 'column', BirthPlaceID
;

EXEC sp_addextendedproperty 'MS_Description', '居住地址。', 'Schema', Secure, 'table', Staff, 'column', ResidenceAddress
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：证件类型标识（关联到CredentialsType表）。', 'Schema', Secure, 'table', Staff, 'column', CredentialsTypeID
;

EXEC sp_addextendedproperty 'MS_Description', '证件编号。', 'Schema', Secure, 'table', Staff, 'column', CredentialsNO
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：主要职位ID（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Staff, 'column', PositionID
;

EXEC sp_addextendedproperty 'MS_Description', '办公电话号码。', 'Schema', Secure, 'table', Staff, 'column', OfficePhoneNO
;

EXEC sp_addextendedproperty 'MS_Description', '移动电话号码。', 'Schema', Secure, 'table', Staff, 'column', MobileNO
;

EXEC sp_addextendedproperty 'MS_Description', '电子邮件地址。', 'Schema', Secure, 'table', Staff, 'column', EmailAddress
;

EXEC sp_addextendedproperty 'MS_Description', '入职日期。', 'Schema', Secure, 'table', Staff, 'column', InductionDate
;

EXEC sp_addextendedproperty 'MS_Description', '是否为试用期员工：Y（是）；N（否）。', 'Schema', Secure, 'table', Staff, 'column', IsProbationary
;

EXEC sp_addextendedproperty 'MS_Description', '试用期长度（单位：月）。', 'Schema', Secure, 'table', Staff, 'column', ProbationLength
;

EXEC sp_addextendedproperty 'MS_Description', '是否自动转正：Y（是）；N（否）。', 'Schema', Secure, 'table', Staff, 'column', AutoRegularized
;

EXEC sp_addextendedproperty 'MS_Description', 'SQL命令执行日志表。', 'Schema', Secure, 'table', SqlLogTrace
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：日志行为唯一标识（关联到BaseLogTrace及ObjectBase表）。', 'Schema', Secure, 'table', SqlLogTrace, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'SQL命令文本。', 'Schema', Secure, 'table', SqlLogTrace, 'column', Command
;

EXEC sp_addextendedproperty 'MS_Description', '命令类型：T（SQL命令串）；S（存储过程）；F（函数）', 'Schema', Secure, 'table', SqlLogTrace, 'column', CommandType
;

EXEC sp_addextendedproperty 'MS_Description', '登录令牌表。', 'Schema', Secure, 'table', SignInToken
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：登录票据唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', SignInToken, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：登录动作标识（关联到SignInAction表）。', 'Schema', Secure, 'table', SignInToken, 'column', ActionID
;

EXEC sp_addextendedproperty 'MS_Description', '登录令牌字符串。', 'Schema', Secure, 'table', SignInToken, 'column', Token
;

EXEC sp_addextendedproperty 'MS_Description', '登录令牌失效时间。', 'Schema', Secure, 'table', SignInToken, 'column', ExpiredTime
;

EXEC sp_addextendedproperty 'MS_Description', '登录、登出日志信息表。', 'Schema', Secure, 'table', SignInLogTrace
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：日志行为唯一标识（关联到BaseLogTrace及ObjectBase表）。', 'Schema', Secure, 'table', SignInLogTrace, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '登录、登出标记：I（登录）；O（登出）。', 'Schema', Secure, 'table', SignInLogTrace, 'column', IOFlag
;

EXEC sp_addextendedproperty 'MS_Description', '登录动作表。', 'Schema', Secure, 'table', SignInAction
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：登录动作唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', SignInAction, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '客户端IP地址。', 'Schema', Secure, 'table', SignInAction, 'column', ClientIP
;

EXEC sp_addextendedproperty 'MS_Description', '主机名称。', 'Schema', Secure, 'table', SignInAction, 'column', HostName
;

EXEC sp_addextendedproperty 'MS_Description', '平台类型：1：PC；2：WP移动设备；3：Android移动设备；4：iOS移动设备；5：Firefox OS移动设备；6：Windows Mobile平台移动设备；7：塞班移动设备；8：MeeGo移动设备；9：黑莓移动设备；-1：未知类型的移动设备。', 'Schema', Secure, 'table', SignInAction, 'column', Platform
;

EXEC sp_addextendedproperty 'MS_Description', '是否成功：Y：（成功的）；N（失败的）。', 'Schema', Secure, 'table', SignInAction, 'column', IsSucceed
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：失败原因代码（关联到PredefinedCode表）。', 'Schema', Secure, 'table', SignInAction, 'column', FailedReasonCodeID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：登录时所用的账户唯一标识（关联到Account表）。如果为NULL，则表示不是已知的账户。', 'Schema', Secure, 'table', SignInAction, 'column', AccountID
;

EXEC sp_addextendedproperty 'MS_Description', '如果AccountID为NULL，则此字段保存错误的账户名称。', 'Schema', Secure, 'table', SignInAction, 'column', UnknownUserID
;

EXEC sp_addextendedproperty 'MS_Description', '角色表。', 'Schema', Secure, 'table', Role
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：角色唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', Role, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '角色名称。', 'Schema', Secure, 'table', Role, 'column', RoleName
;

EXEC sp_addextendedproperty 'MS_Description', '角色代码。', 'Schema', Secure, 'table', Role, 'column', RoleCode
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：子系统标识（关联到Subsystem表）。', 'Schema', Secure, 'table', Role, 'column', SysID
;

EXEC sp_addextendedproperty 'MS_Description', '职位汇报关系表。', 'Schema', Secure, 'table', PositionRelation
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：汇报关系唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', PositionRelation, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：上一级职位标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', PositionRelation, 'column', SuperiorID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：当前职位标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', PositionRelation, 'column', CurrentID
;

EXEC sp_addextendedproperty 'MS_Description', '职位信息表。', 'Schema', Secure, 'table', Position
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：职位信息唯一标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Position, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：组织标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Position, 'column', OrganizationID
;

EXEC sp_addextendedproperty 'MS_Description', '人员兼职关系表。', 'Schema', Secure, 'table', ParttimeRelation
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：兼职关系唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', ParttimeRelation, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：人员标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', ParttimeRelation, 'column', StaffID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：兼职职位标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', ParttimeRelation, 'column', PositionID
;

EXEC sp_addextendedproperty 'MS_Description', '组织机构对象基础属性表。', 'Schema', Secure, 'table', OrganizationObject
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：组织机构对象唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', OrganizationObject, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '组织机构对象名称。', 'Schema', Secure, 'table', OrganizationObject, 'column', ObjectName
;

EXEC sp_addextendedproperty 'MS_Description', '父组织机构对象ID。', 'Schema', Secure, 'table', OrganizationObject, 'column', ParentObjectID
;

EXEC sp_addextendedproperty 'MS_Description', '组织机构对象类别：1：组织；2：人员组；3：职位；4：人员。', 'Schema', Secure, 'table', OrganizationObject, 'column', Category
;

EXEC sp_addextendedproperty 'MS_Description', '排序标识。', 'Schema', Secure, 'table', OrganizationObject, 'column', SortID
;

EXEC sp_addextendedproperty 'MS_Description', '对象虚名称。', 'Schema', Secure, 'table', OrganizationObject, 'column', VirtualName
;

EXEC sp_addextendedproperty 'MS_Description', '组织信息表。', 'Schema', Secure, 'table', Organization
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：组织唯一标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Organization, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：此组织的主要负责人标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Organization, 'column', PrincipalStaffID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：主要负责的职位标识（关联到OrganizationObject表）。', 'Schema', Secure, 'table', Organization, 'column', PrincipalPositionID
;

EXEC sp_addextendedproperty 'MS_Description', '基础日志信息表。', 'Schema', Secure, 'table', BaseLogTrace
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：日志行为唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', BaseLogTrace, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '调用的方法名称。', 'Schema', Secure, 'table', BaseLogTrace, 'column', MethodName
;

EXEC sp_addextendedproperty 'MS_Description', '包含方法的类型名称。', 'Schema', Secure, 'table', BaseLogTrace, 'column', TypeName
;

EXEC sp_addextendedproperty 'MS_Description', '版本号。', 'Schema', Secure, 'table', BaseLogTrace, 'column', Version
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：调用者标识（关联到Account表）。', 'Schema', Secure, 'table', BaseLogTrace, 'column', CallAccountID
;

EXEC sp_addextendedproperty 'MS_Description', '系统管理员账户表。', 'Schema', Secure, 'table', Administrator
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：系统管理员唯一标识（关联到Account、ObjectBase表）。', 'Schema', Secure, 'table', Administrator, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '是否为默认系统管理员账户：Y（是）；N（否）。默认的系统管理员不可删除。', 'Schema', Secure, 'table', Administrator, 'column', IsDefault
;

EXEC sp_addextendedproperty 'MS_Description', '是否集成Windows账户：Y（是）；N（否）。', 'Schema', Secure, 'table', Administrator, 'column', WindowsIntergrated
;

EXEC sp_addextendedproperty 'MS_Description', '系统账户基本信息表。', 'Schema', Secure, 'table', Account
;
EXEC sp_addextendedproperty 'MS_Description', 'PK：系统账户唯一标识（关联到ObjectBase表）。', 'Schema', Secure, 'table', Account, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '账户。', 'Schema', Secure, 'table', Account, 'column', UserID
;

EXEC sp_addextendedproperty 'MS_Description', '口令。', 'Schema', Secure, 'table', Account, 'column', Passphrase
;

EXEC sp_addextendedproperty 'MS_Description', '是否为空密码：Y（是）、N（否）。', 'Schema', Secure, 'table', Account, 'column', EmptyPass
;

EXEC sp_addextendedproperty 'MS_Description', '系统预定义代码表。', 'Schema', Basic, 'table', PredefinedCode
;
EXEC sp_addextendedproperty 'MS_Description', 'PK & FK：系统预定义代码唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', PredefinedCode, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：应用模块唯一标识（关联到ObjectBase、ApplicationBlock表）。', 'Schema', Basic, 'table', PredefinedCode, 'column', BlockID
;

EXEC sp_addextendedproperty 'MS_Description', '代码。', 'Schema', Basic, 'table', PredefinedCode, 'column', Code
;

EXEC sp_addextendedproperty 'MS_Description', '对象基本属性表。', 'Schema', Basic, 'table', ObjectBase
;
EXEC sp_addextendedproperty 'MS_Description', 'PK：对象唯一标识。', 'Schema', Basic, 'table', ObjectBase, 'column', ObjectID
;

EXEC sp_addextendedproperty 'MS_Description', '是否已经被逻辑删除：Y（是）；N（否）。', 'Schema', Basic, 'table', ObjectBase, 'column', IsRemoved
;

EXEC sp_addextendedproperty 'MS_Description', '是否被启用：Y（是）；N（否）。', 'Schema', Basic, 'table', ObjectBase, 'column', Enabled
;

EXEC sp_addextendedproperty 'MS_Description', '是否可见：Y（可见的）；N（隐藏的）。', 'Schema', Basic, 'table', ObjectBase, 'column', Visible
;

EXEC sp_addextendedproperty 'MS_Description', '对外公开的唯一标识。', 'Schema', Basic, 'table', ObjectBase, 'column', OpenID
;

EXEC sp_addextendedproperty 'MS_Description', '对象被创建的时间。', 'Schema', Basic, 'table', ObjectBase, 'column', IsCreatedTime
;

EXEC sp_addextendedproperty 'MS_Description', '最后一次被修改的时间。', 'Schema', Basic, 'table', ObjectBase, 'column', LastModifiedTime
;

EXEC sp_addextendedproperty 'MS_Description', '对象被修改的次数。', 'Schema', Basic, 'table', ObjectBase, 'column', IsModifiedTimes
;

EXEC sp_addextendedproperty 'MS_Description', '对象的备注信息。', 'Schema', Basic, 'table', ObjectBase, 'column', Comments
;

EXEC sp_addextendedproperty 'MS_Description', '更新补丁发布信息表。', 'Schema', Basic, 'table', HotfixRelease
;
EXEC sp_addextendedproperty 'MS_Description', 'PK & FK：更新补丁唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', HotfixRelease, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：更新代码ID（关联到PredefinedCode表）。', 'Schema', Basic, 'table', HotfixRelease, 'column', CodeID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：需要更新的模块标识（关联到ApplicationBlock表）。', 'Schema', Basic, 'table', HotfixRelease, 'column', BlockID
;

EXEC sp_addextendedproperty 'MS_Description', '更新补丁的版本号。', 'Schema', Basic, 'table', HotfixRelease, 'column', Version
;

EXEC sp_addextendedproperty 'MS_Description', '功能概述。', 'Schema', Basic, 'table', HotfixRelease, 'column', FeatureSummary
;

EXEC sp_addextendedproperty 'MS_Description', '发布日期。', 'Schema', Basic, 'table', HotfixRelease, 'column', ReleaseDate
;

EXEC sp_addextendedproperty 'MS_Description', '是否为重要更新：Y（是）；N（否）。', 'Schema', Basic, 'table', HotfixRelease, 'column', IsImportant
;

EXEC sp_addextendedproperty 'MS_Description', '全球区域定义表。', 'Schema', Basic, 'table', GlobalRegion
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：区域唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', GlobalRegion, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '区域名称。', 'Schema', Basic, 'table', GlobalRegion, 'column', RegionName
;

EXEC sp_addextendedproperty 'MS_Description', '父区域标识。', 'Schema', Basic, 'table', GlobalRegion, 'column', ParentRegionID
;

EXEC sp_addextendedproperty 'MS_Description', '文件流表。', 'Schema', Basic, 'table', FileStream
;
EXEC sp_addextendedproperty 'MS_Description', 'PK & FK：文件对象唯一标识（关联到FileObject表）。', 'Schema', Basic, 'table', FileStream, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '文件流数据。', 'Schema', Basic, 'table', FileStream, 'column', Stream
;

EXEC sp_addextendedproperty 'MS_Description', '文件对象信息表。', 'Schema', Basic, 'table', FileObject
;
EXEC sp_addextendedproperty 'MS_Description', 'PK & FK：文件对象唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', FileObject, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '文件原始名称。', 'Schema', Basic, 'table', FileObject, 'column', RawName
;

EXEC sp_addextendedproperty 'MS_Description', '文件扩展名。', 'Schema', Basic, 'table', FileObject, 'column', ExtensionName
;

EXEC sp_addextendedproperty 'MS_Description', '文件类型对应的Http Mime类型。', 'Schema', Basic, 'table', FileObject, 'column', MimeType
;

EXEC sp_addextendedproperty 'MS_Description', '文件长度。', 'Schema', Basic, 'table', FileObject, 'column', FileSize
;

EXEC sp_addextendedproperty 'MS_Description', '是否保存到数据库：Y（以保存到数据库）；N（未保存到数据库）。', 'Schema', Basic, 'table', FileObject, 'column', SaveToDB
;

EXEC sp_addextendedproperty 'MS_Description', '是否保存到服务器物理硬盘中：Y（是）；N（否）。', 'Schema', Basic, 'table', FileObject, 'column', SaveToDisk
;

EXEC sp_addextendedproperty 'MS_Description', '文件的物理路径。', 'Schema', Basic, 'table', FileObject, 'column', PhysicalPath
;

EXEC sp_addextendedproperty 'MS_Description', '文件对象映射关系表。', 'Schema', Basic, 'table', FileMapRelation
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：关系唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', FileMapRelation, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：文件对象标识（关联到FileObject表）。', 'Schema', Basic, 'table', FileMapRelation, 'column', FileID
;

EXEC sp_addextendedproperty 'MS_Description', 'FK：关联的对象唯一标识。', 'Schema', Basic, 'table', FileMapRelation, 'column', AssociatedObjectID
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型表。', 'Schema', Basic, 'table', CredentialsType
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：证件类型唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', CredentialsType, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型名称。', 'Schema', Basic, 'table', CredentialsType, 'column', TypeName
;

EXEC sp_addextendedproperty 'MS_Description', '系统模块表。', 'Schema', Basic, 'table', ApplicationBlock
;
EXEC sp_addextendedproperty 'MS_Description', 'PK&FK：系统模块唯一标识（关联到ObjectBase表）。', 'Schema', Basic, 'table', ApplicationBlock, 'column', UniqueID
;

EXEC sp_addextendedproperty 'MS_Description', '应用模块名称（简体中文）。', 'Schema', Basic, 'table', ApplicationBlock, 'column', BlockName
;

EXEC sp_addextendedproperty 'MS_Description', '上级模块ID（关联到ApplicationBlock、ObjectBase表）。', 'Schema', Basic, 'table', ApplicationBlock, 'column', ParentBlockID
;

EXEC sp_addextendedproperty 'MS_Description', '应用模块代码。', 'Schema', Basic, 'table', ApplicationBlock, 'column', Code
;

EXEC sp_addextendedproperty 'MS_Description', '扩展信息。', 'Schema', Basic, 'table', ApplicationBlock, 'column', XExpando
;
