//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace EnterpriseServices.SecurityService.API.ParamsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ParametersServiceSoap", Namespace="urn:Masterduner@Yeah.net")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DbHelper))]
    public partial class ParametersService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCredentialsTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlaceRegionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ParametersService() {
            this.Url = global::EnterpriseServices.SecurityService.API.Properties.Settings.Default.EH_Security_OpenAPIs_SDK_ParamsService_ParametersService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCredentialsTypesCompletedEventHandler GetCredentialsTypesCompleted;
        
        /// <remarks/>
        public event GetPlaceRegionsCompletedEventHandler GetPlaceRegionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetCredentialsTypes", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserCredentialsType[] GetCredentialsTypes() {
            object[] results = this.Invoke("GetCredentialsTypes", new object[0]);
            return ((UserCredentialsType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCredentialsTypesAsync() {
            this.GetCredentialsTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetCredentialsTypesAsync(object userState) {
            if ((this.GetCredentialsTypesOperationCompleted == null)) {
                this.GetCredentialsTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCredentialsTypesOperationCompleted);
            }
            this.InvokeAsync("GetCredentialsTypes", new object[0], this.GetCredentialsTypesOperationCompleted, userState);
        }
        
        private void OnGetCredentialsTypesOperationCompleted(object arg) {
            if ((this.GetCredentialsTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCredentialsTypesCompleted(this, new GetCredentialsTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/GetPlaceRegions", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PlaceRegion[] GetPlaceRegions() {
            object[] results = this.Invoke("GetPlaceRegions", new object[0]);
            return ((PlaceRegion[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPlaceRegionsAsync() {
            this.GetPlaceRegionsAsync(null);
        }
        
        /// <remarks/>
        public void GetPlaceRegionsAsync(object userState) {
            if ((this.GetPlaceRegionsOperationCompleted == null)) {
                this.GetPlaceRegionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlaceRegionsOperationCompleted);
            }
            this.InvokeAsync("GetPlaceRegions", new object[0], this.GetPlaceRegionsOperationCompleted, userState);
        }
        
        private void OnGetPlaceRegionsOperationCompleted(object arg) {
            if ((this.GetPlaceRegionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlaceRegionsCompleted(this, new GetPlaceRegionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class UserCredentialsType : ParameterDeclaration {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceRegion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCredentialsType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public abstract partial class ParameterDeclaration : DbHelper {
        
        private System.Guid uniqueIDField;
        
        private string valueField;
        
        private string openIDField;
        
        private bool enabledField;
        
        /// <remarks/>
        public System.Guid UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string OpenID {
            get {
                return this.openIDField;
            }
            set {
                this.openIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterDeclaration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceRegion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCredentialsType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class DbHelper {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public partial class PlaceRegion : ParameterDeclaration {
        
        private System.Guid parentIDField;
        
        /// <remarks/>
        public System.Guid ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCredentialsTypesCompletedEventHandler(object sender, GetCredentialsTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCredentialsTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCredentialsTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserCredentialsType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserCredentialsType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPlaceRegionsCompletedEventHandler(object sender, GetPlaceRegionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlaceRegionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlaceRegionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlaceRegion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlaceRegion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591