//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace EnterpriseServices.SecurityService.API.BehaviorService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserBehaviorServiceSoap", Namespace="urn:Masterduner@Yeah.net")]
    public partial class UserBehaviorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TraceInOutBehaviorOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraceOperateBehaviorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserBehaviorService() {
            this.Url = global::EnterpriseServices.SecurityService.API.Properties.Settings.Default.EH_Security_OpenAPIs_SDK_BehaviorService_UserBehaviorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TraceInOutBehaviorCompletedEventHandler TraceInOutBehaviorCompleted;
        
        /// <remarks/>
        public event TraceOperateBehaviorCompletedEventHandler TraceOperateBehaviorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/TraceInOutBehavior", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TraceInOutBehavior(string methodName, string typeName, string version, InOut mark, string userName) {
            this.Invoke("TraceInOutBehavior", new object[] {
                        methodName,
                        typeName,
                        version,
                        mark,
                        userName});
        }
        
        /// <remarks/>
        public void TraceInOutBehaviorAsync(string methodName, string typeName, string version, InOut mark, string userName) {
            this.TraceInOutBehaviorAsync(methodName, typeName, version, mark, userName, null);
        }
        
        /// <remarks/>
        public void TraceInOutBehaviorAsync(string methodName, string typeName, string version, InOut mark, string userName, object userState) {
            if ((this.TraceInOutBehaviorOperationCompleted == null)) {
                this.TraceInOutBehaviorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraceInOutBehaviorOperationCompleted);
            }
            this.InvokeAsync("TraceInOutBehavior", new object[] {
                        methodName,
                        typeName,
                        version,
                        mark,
                        userName}, this.TraceInOutBehaviorOperationCompleted, userState);
        }
        
        private void OnTraceInOutBehaviorOperationCompleted(object arg) {
            if ((this.TraceInOutBehaviorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraceInOutBehaviorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Masterduner@Yeah.net/TraceOperateBehavior", RequestNamespace="urn:Masterduner@Yeah.net", ResponseNamespace="urn:Masterduner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TraceOperateBehavior(string methodName, string typeName, string version, System.Guid userID) {
            this.Invoke("TraceOperateBehavior", new object[] {
                        methodName,
                        typeName,
                        version,
                        userID});
        }
        
        /// <remarks/>
        public void TraceOperateBehaviorAsync(string methodName, string typeName, string version, System.Guid userID) {
            this.TraceOperateBehaviorAsync(methodName, typeName, version, userID, null);
        }
        
        /// <remarks/>
        public void TraceOperateBehaviorAsync(string methodName, string typeName, string version, System.Guid userID, object userState) {
            if ((this.TraceOperateBehaviorOperationCompleted == null)) {
                this.TraceOperateBehaviorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraceOperateBehaviorOperationCompleted);
            }
            this.InvokeAsync("TraceOperateBehavior", new object[] {
                        methodName,
                        typeName,
                        version,
                        userID}, this.TraceOperateBehaviorOperationCompleted, userState);
        }
        
        private void OnTraceOperateBehaviorOperationCompleted(object arg) {
            if ((this.TraceOperateBehaviorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraceOperateBehaviorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Masterduner@Yeah.net")]
    public enum InOut {
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        Out,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TraceInOutBehaviorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TraceOperateBehaviorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591