//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseServices.ManagementClient.Operations.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnterpriseServices.ManagementClient.Operations.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About(&amp;A) Management Studio 的本地化字符串。
        /// </summary>
        public static string AboutClient {
            get {
                return ResourceManager.GetString("AboutClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrators 的本地化字符串。
        /// </summary>
        public static string AdminGroup {
            get {
                return ResourceManager.GetString("AdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElitesHunter Management Studio 的本地化字符串。
        /// </summary>
        public static string ApplicationCaption {
            get {
                return ResourceManager.GetString("ApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication failed! 的本地化字符串。
        /// </summary>
        public static string AuthenticateFailed {
            get {
                return ResourceManager.GetString("AuthenticateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization Management 的本地化字符串。
        /// </summary>
        public static string AuthorizationManagement {
            get {
                return ResourceManager.GetString("AuthorizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorize 的本地化字符串。
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Blocks 的本地化字符串。
        /// </summary>
        public static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Codes 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect To Server 的本地化字符串。
        /// </summary>
        public static string ConnectToServer {
            get {
                return ResourceManager.GetString("ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to exit the management studio? 的本地化字符串。
        /// </summary>
        public static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please run this program as an administrator! 的本地化字符串。
        /// </summary>
        public static string IsNotAdministrator {
            get {
                return ResourceManager.GetString("IsNotAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior Trace 的本地化字符串。
        /// </summary>
        public static string LoggingViewer {
            get {
                return ResourceManager.GetString("LoggingViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElitesHunter Management Studio 的本地化字符串。
        /// </summary>
        public static string MainWindowCaption {
            get {
                return ResourceManager.GetString("MainWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Organization 的本地化字符串。
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Organization Management 的本地化字符串。
        /// </summary>
        public static string OrganizationManagement {
            get {
                return ResourceManager.GetString("OrganizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string ParameterDeclaration {
            get {
                return ResourceManager.GetString("ParameterDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Expiration Policy 的本地化字符串。
        /// </summary>
        public static string PasswordExpirationPolicy {
            get {
                return ResourceManager.GetString("PasswordExpirationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission 的本地化字符串。
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Line 的本地化字符串。
        /// </summary>
        public static string ReportLine {
            get {
                return ResourceManager.GetString("ReportLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Authentication 的本地化字符串。
        /// </summary>
        public static string ServerAuthenticate {
            get {
                return ResourceManager.GetString("ServerAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In Method 的本地化字符串。
        /// </summary>
        public static string SignInMethod {
            get {
                return ResourceManager.GetString("SignInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff 的本地化字符串。
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User &quot; {0} &quot; is trying to start management studio! This process needs to verify that he is in the Windows Administrators group, if the validation is successful, it will start. 的本地化字符串。
        /// </summary>
        public static string StartupLogMessage {
            get {
                return ResourceManager.GetString("StartupLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Authentication 的本地化字符串。
        /// </summary>
        public static string WindowsNTAuthenticate {
            get {
                return ResourceManager.GetString("WindowsNTAuthenticate", resourceCulture);
            }
        }
    }
}
