//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseServices.SecurityService.API.Configuration
{


    /// <summary>
    /// 服务引用配置。
    /// </summary>
    public sealed partial class ServiceReferenceUrlConfigureElement : global::System.Configuration.ConfigurationElement
    {

        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion

        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string NamePropertyName = "name";

        /// <summary>
        /// Gets or sets 设置或获取服务名称。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("设置或获取服务名称。")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement.NamePropertyName, IsRequired = true, IsKey = true, IsDefaultCollection = false)]
        public string Name
        {
            get
            {
                return ((string)(base[global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement.NamePropertyName]));
            }
            set
            {
                base[global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement.NamePropertyName] = value;
            }
        }
        #endregion

        #region Url Property
        /// <summary>
        /// The XML name of the <see cref="Url"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string UrlPropertyName = "url";

        /// <summary>
        /// Gets or sets 设置或获取服务地址。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("设置或获取服务地址。")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement.UrlPropertyName, IsRequired = true, IsKey = false, IsDefaultCollection = false)]
        public string Url
        {
            get
            {
                return ((string)(base[global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement.UrlPropertyName]));
            }
            set
            {
                base[global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement.UrlPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace EnterpriseServices.SecurityService.API.Configuration
{


    /// <summary>
    /// ServiceReferenceUrlConfigureElement集合。
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement), CollectionType = global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName = global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElementCollection.ServiceReferenceUrlConfigureElementPropertyName)]
    public sealed partial class ServiceReferenceUrlConfigureElementCollection : global::System.Configuration.ConfigurationElementCollection
    {

        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ServiceReferenceUrlConfigureElementPropertyName = "add";
        #endregion

        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }

        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElementCollection.ServiceReferenceUrlConfigureElementPropertyName;
            }
        }

        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElementCollection.ServiceReferenceUrlConfigureElementPropertyName);
        }

        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement)(element)).Name;
        }

        /// <summary>
        /// Creates a new <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement();
        }
        #endregion

        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement this[int index]
        {
            get
            {
                return ((global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement)(base.BaseGet(index)));
            }
        }

        /// <summary>
        /// Gets the <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement this[object name]
        {
            get
            {
                return ((global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElement)(base.BaseGet(name)));
            }
        }
        #endregion

        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace EnterpriseServices.SecurityService.API.Configuration
{


    /// <summary>
    /// 服务引用地址配置。
    /// </summary>
    public sealed partial class ApiServiceReferenceUrlSection : global::System.Configuration.ConfigurationSection
    {

        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";

        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.XmlnsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.XmlnsPropertyName]));
            }
        }
        #endregion

        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion

        #region BaseUrl Property
        /// <summary>
        /// The XML name of the <see cref="BaseUrl"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string BaseUrlPropertyName = "baseUrl";

        /// <summary>
        /// Gets or sets 设置或获取服务基地址。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("设置或获取服务基地址。")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.BaseUrlPropertyName, IsRequired = true, IsKey = false, IsDefaultCollection = false)]
        public string BaseUrl
        {
            get
            {
                return ((string)(base[global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.BaseUrlPropertyName]));
            }
            set
            {
                base[global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.BaseUrlPropertyName] = value;
            }
        }
        #endregion

        #region References Property
        /// <summary>
        /// The XML name of the <see cref="References"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ReferencesPropertyName = "";

        /// <summary>
        /// Gets or sets the References.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The References.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.ReferencesPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = true)]
        public global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElementCollection References
        {
            get
            {
                return ((global::EnterpriseServices.SecurityService.API.Configuration.ServiceReferenceUrlConfigureElementCollection)(base[global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.ReferencesPropertyName]));
            }
            set
            {
                base[global::EnterpriseServices.SecurityService.API.Configuration.ApiServiceReferenceUrlSection.ReferencesPropertyName] = value;
            }
        }
        #endregion
    }
}
