//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseServices.SecurityService.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnterpriseServices.SecurityService.Framework.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 附加的方法监听器异常！ 的本地化字符串。
        /// </summary>
        public static string ExtraMonitorError {
            get {
                return ResourceManager.GetString("ExtraMonitorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户没有系统管理员权限！ 的本地化字符串。
        /// </summary>
        public static string IsNotSystemAdministratorError {
            get {
                return ResourceManager.GetString("IsNotSystemAdministratorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法监听器异常！ 的本地化字符串。
        /// </summary>
        public static string MonitorError {
            get {
                return ResourceManager.GetString("MonitorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户不是正式员工！ 的本地化字符串。
        /// </summary>
        public static string NotFormallyStaffError {
            get {
                return ResourceManager.GetString("NotFormallyStaffError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户不在指定的组织中！ 的本地化字符串。
        /// </summary>
        public static string NotInOrganizationError {
            get {
                return ResourceManager.GetString("NotInOrganizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户是兼职的！ 的本地化字符串。
        /// </summary>
        public static string ParttimeError {
            get {
                return ResourceManager.GetString("ParttimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户的职位与指定职位不同！ 的本地化字符串。
        /// </summary>
        public static string PositionError {
            get {
                return ResourceManager.GetString("PositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的用户已经被禁用！ 的本地化字符串。
        /// </summary>
        public static string UserDisabledError {
            get {
                return ResourceManager.GetString("UserDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户没有权限执行此方法！ 的本地化字符串。
        /// </summary>
        public static string WithoutPermissionError {
            get {
                return ResourceManager.GetString("WithoutPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的登录口令！ 的本地化字符串。
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能在系统中找到指定的用户名！ 的本地化字符串。
        /// </summary>
        public static string WrongUserNameError {
            get {
                return ResourceManager.GetString("WrongUserNameError", resourceCulture);
            }
        }
    }
}
